name: Deploy project to our server

on:
  push:
    branches:
      - deploy

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.codearif.com
          username: chat@chat-backend.codearif.com
          password: "*FGLGND,TO.o"
